import { Duration, RemovalPolicy } from 'aws-cdk-lib';

import type { EnvSettings } from '../env';

export const prod: EnvSettings = {
  extAPIResourceRemovalPolicy: RemovalPolicy.RETAIN,
  backupVaultRemovalPolicy: RemovalPolicy.RETAIN,
  loadBalancerDeletionProtection: true,
  addWeeklyBackups: true,
  natGateways: 2,
  databaseRemovalPolicy: RemovalPolicy.RETAIN,
  databaseDeletionProtection: true,
  requestEventDynamoRemovalPolicy: RemovalPolicy.RETAIN,
  websiteSubDomain: 'app',
  hasuraEcrRepoName: 'hasura/graphql-engine',
  permitEcrRepoName: 'permitio/pdp-v2',
  trpcEcrRepoName: 'risksmart/trpc-api',
  integrationsEcrRepoName: 'risksmart/integrations',
  extAPIEcrRepoName: 'risksmart/external-api',
  mcpEcrRepoName: 'risksmart/mcp',
  tenantDeployerEcrRepoName: 'risksmart/tenant-deployer',
  apiAuthSubDomain: 'api',
  hasuraHealthCheck: {
    // Increasing health check timeout for dev, so we don't need to increase specs, but can deploy hasura without the container being killed
    timeout: Duration.seconds(30),
  },
  hasuraContainerSettings: {
    cpu: 2048,
    memoryLimitMiB: 4096,
  },
  hasuraTaskSettings: {
    cpu: 2048,
    memoryLimitMiB: 4096,
  },
  isInternalAlbEnabled: true,
  apiDistributionWebAclArn:
    'arn:aws:wafv2:us-east-1:826351825809:global/webacl/' +
    'prod-us-east-1-api-waf/5ef65199-e558-4bb1-970b-2d4d716dc032',
  thirdPartyPortalWebAclArn:
    'arn:aws:wafv2:us-east-1:826351825809:global/webacl/' +
    'prod-us-east-1-tpp-waf/3454474c-2fb2-42a2-b1c3-c220a6c7ae37',
  tenants: [
    {
      albPriority: 1,
      name: 'MultiTenant',
      databaseReaderInstanceCount: 1,
      maxDbCapacity: 50,
      minDbCapacity: 1,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: true,
      snapshotId: 'multi-tenant-snapshot-v1',
      databaseEnableProxy: true,
      databaseMasterUsernameOverride: 'hasura_user',
      region: 'eu-west-2',
      customers: ['multi-tenant'],
    },
    {
      albPriority: 2,
      name: 'OctoEnergy',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['octopus-ev', 'octopus-energy'],
    },
    {
      albPriority: 3,
      name: 'CanaryRisk',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['canary-corp'],
    },
    {
      albPriority: 4,
      name: 'DLA',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['dla'],
    },
    {
      albPriority: 5,
      name: 'MSL',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['msl'],
    },
    {
      albPriority: 6,
      name: 'JenstenGroup',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['jensten'],
    },
    {
      albPriority: 7,
      name: 'Education',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['barnett-waddingham'],
    },
    {
      albPriority: 9,
      name: 'sandbox',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 1,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['sales'],
    },
    {
      albPriority: 10,
      name: 'rightmove',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['rightmove'],
    },
    {
      albPriority: 11,
      name: 'pxc',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['pxc'],
    },
    {
      albPriority: 12,
      name: 'autotrader',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['autotrader'],
    },
    {
      albPriority: 13,
      name: 'krakentechnologies',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseMasterUsernameOverride: 'hasura_user',
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['kraken-technologies'],
    },
    {
      albPriority: 14,
      name: 'elementisglobal',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['elementis-global'],
    },
    {
      albPriority: 15,
      name: 'skyscanner',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['skyscanner'],
    },
    {
      albPriority: 16,
      name: 'betfred',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['betfred'],
    },
    {
      albPriority: 17,
      name: 'petervardy',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['peter-vardy'],
    },
    {
      albPriority: 18,
      name: 'admiral',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['admiral'],
    },
    {
      albPriority: 19,
      name: 'hodgebank',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['hodge-bank'],
    },
    {
      albPriority: 20,
      name: 'dojo',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['dojo'],
    },
    {
      albPriority: 21,
      name: 'amberriver',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['amber-river'],
    },
    {
      albPriority: 22,
      name: 'gfhfinancial',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['gfh-financial'],
    },
    {
      albPriority: 23,
      name: 'clearstreet',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['clear-street'],
    },
    {
      albPriority: 24,
      name: 'rslite',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['rs-lite'],
    },
    {
      albPriority: 25,
      name: 'soprasteria',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['sopra-steria'],
    },
    {
      albPriority: 26,
      name: 'mkspamp',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['mks-pamp'],
    },
    {
      albPriority: 27,
      name: 'argentis',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['argentis'],
    },
    {
      albPriority: 28,
      name: 'mortgageadvicebureau',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['mortgage-advice-bureau'],
    },
    {
      albPriority: 29,
      name: 'maven',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      databaseEnableProxy: true,
      region: 'eu-west-2',
      customers: ['maven'],
    },
    {
      albPriority: 30,
      name: 'gousto',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 50,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['gousto'],
    },
  ],
};
