import { Duration, RemovalPolicy } from 'aws-cdk-lib';

import type { EnvSettings } from '../env';

export const staging: EnvSettings = {
  extAPIResourceRemovalPolicy: RemovalPolicy.RETAIN,
  backupVaultRemovalPolicy: RemovalPolicy.RETAIN,
  loadBalancerDeletionProtection: true,
  addWeeklyBackups: false,
  natGateways: 1,
  databaseRemovalPolicy: RemovalPolicy.SNAPSHOT,
  databaseDeletionProtection: false,
  requestEventDynamoRemovalPolicy: RemovalPolicy.DESTROY,
  websiteSubDomain: 'staging',
  hasuraEcrRepoName: 'hasura/graphql-engine',
  permitEcrRepoName: 'permitio/pdp-v2',
  trpcEcrRepoName: 'risksmart/trpc-api',
  integrationsEcrRepoName: 'risksmart/integrations',
  extAPIEcrRepoName: 'risksmart/external-api',
  mcpEcrRepoName: 'risksmart/mcp',
  tenantDeployerEcrRepoName: 'risksmart/tenant-deployer',
  apiAuthSubDomain: 'staging',
  hasuraHealthCheck: {
    // Increasing health check timeout for dev, so we don't need to increase specs, but can deploy hasura without the container being killed
    timeout: Duration.seconds(30),
  },
  hasuraContainerSettings: {
    cpu: 2048,
    memoryLimitMiB: 4096,
  },
  hasuraTaskSettings: {
    cpu: 2048,
    memoryLimitMiB: 4096,
  },
  isInternalAlbEnabled: true,
  apiDistributionWebAclArn: '',
  thirdPartyPortalWebAclArn: '',
  tenants: [
    {
      albPriority: 1,
      name: 'MultiTenant',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 5,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: true,
      snapshotId: 'multi-tenant-snapshot-v1',
      databaseEnableProxy: true,
      databaseMasterUsernameOverride: 'hasura_user',
      region: 'eu-west-2',
      customers: ['engineering'],
    },
    {
      albPriority: 2,
      name: 'OctoEnergy',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 5,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'eu-west-2',
      customers: ['engineering'],
    },
    {
      albPriority: 4,
      name: 'TestTenantUS',
      databaseReaderInstanceCount: 0,
      maxDbCapacity: 5,
      minDbCapacity: 0.5,
      backupRetentionDays: 30,
      containerPort: 8080,
      dbMigration: false,
      region: 'us-east-1',
      riskSmartRegionID: 'US-1',
      customers: ['engineering'],
    },
  ],
};
