import { AppetiteType } from '@risksmart-app/domain/src/types/consts';
import type { InferInsertModel } from '@risksmart-app/drizzle/src/db';
import { randomUUID } from 'crypto';

export const buildAppetite = ({
  orgKey,
  userId,
  appetiteId,
  overrides,
}: {
  orgKey: string;
  userId: string;
  appetiteId?: string;
  overrides?: Partial<InferInsertModel<'appetite'>>;
}): Omit<InferInsertModel<'appetite'>, 'SequentialId'> => ({
  // SequentialId is auto-generated by the DB, should not be mocked or tested
  Id: appetiteId || randomUUID(),
  LowerAppetite: 2,
  UpperAppetite: 4,
  Statement: 'Test appetite statement',
  EffectiveDate: new Date().toISOString(),
  AppetiteType: AppetiteType.Risk,
  ImpactAppetite: 3,
  LikelihoodAppetite: 2,
  ImpactId: null,
  CustomAttributeData: {},
  OrgKey: orgKey,
  CreatedByUser: userId,
  CreatedAtTimestamp: undefined,
  ModifiedByUser: userId,
  ModifiedAtTimestamp: undefined,
  ...overrides,
});
