import { RiskTreatmentType } from '@risksmart-app/domain/src/types/consts';
import type { InferInsertModel } from '@risksmart-app/drizzle/src/db';
import { randomUUID } from 'crypto';

export const buildEnterpriseRisk = ({
  orgKey,
  userId,
  enterpriseRiskId,
  overrides,
}: {
  orgKey: string;
  userId: string;
  enterpriseRiskId?: string;
  overrides?: Partial<InferInsertModel<'enterprise_risk'>>;
}): Omit<InferInsertModel<'enterprise_risk'>, 'SequentialId'> => ({
  // SequentialId is auto-generated by the DB, should not be mocked or tested
  Description: 'Some enterprise risk description',
  Title: 'Enterprise risk',
  CreatedAtTimestamp: undefined,
  ModifiedAtTimestamp: undefined,
  Id: enterpriseRiskId || randomUUID(),
  Tier: 1,
  ParentId: null,
  CreatedByUser: userId,
  ModifiedByUser: userId,
  OrgKey: orgKey,
  Treatment: RiskTreatmentType.Terminate,
  ...overrides,
});
