import type { InferInsertModel } from '@risksmart-app/drizzle/src/db';
import { randomUUID } from 'crypto';

export const buildImpactRating = ({
  orgKey,
  userId,
  impactId,
  ratedItemId,
  overrides,
}: {
  orgKey: string;
  userId: string;
  impactId: string;
  ratedItemId: string;
  overrides?: Partial<InferInsertModel<'impact_rating'>>;
}): Omit<InferInsertModel<'impact_rating'>, 'SequentialId'> => ({
  // SequentialId is auto-generated by the DB, should not be mocked or tested
  Id: randomUUID(),
  ImpactId: impactId,
  RatedItemId: ratedItemId,
  Rating: 3,
  TestDate: '2024-01-15T10:00:00Z',
  CustomAttributeData: {},
  OrgKey: orgKey,
  CreatedByUser: userId,
  CreatedAtTimestamp: undefined,
  ModifiedByUser: userId,
  ModifiedAtTimestamp: undefined,
  CompletedBy: null,
  RatingType: 'rating',
  Likelihood: 2,
  ...overrides,
});
