import type { InferInsertModel } from '@risksmart-app/drizzle/src/db';
import { randomUUID } from 'crypto';

export const buildImpact = ({
  orgKey,
  userId,
  impactId,
  overrides,
}: {
  orgKey: string;
  userId: string;
  impactId?: string;
  overrides?: Partial<InferInsertModel<'impact'>>;
}): Omit<InferInsertModel<'impact'>, 'SequentialId'> => ({
  // SequentialId is auto-generated by the DB, should not be mocked or tested
  Id: impactId || randomUUID(),
  Name: 'Test Impact',
  Rationale: 'Test impact rationale',
  ImpactAppetite: 3,
  LikelihoodAppetite: 2,
  CustomAttributeData: {},
  OrgKey: orgKey,
  CreatedByUser: userId,
  CreatedAtTimestamp: undefined,
  ModifiedByUser: userId,
  ModifiedAtTimestamp: undefined,
  RatingGuidance: 'Test rating guidance',
  ...overrides,
});
