name: Template / SST Deploy

permissions:
  actions: write
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      runner_label:
        required: false
        type: string
        default: 'sprinters:aws:eu-west-2:ubuntu-latest:m7i-flex.large:spot=false'
      env:
        required: true
        type: string
      region:
        required: true
        type: string
      is_risksmart_region:
        required: true
        type: boolean
      domain_prefix:
        required: true
        type: string
      resource_prefix:
        required: true
        type: string
      app_or_risksmart_app:
        required: true
        type: string
      react_app_auth0_domain:
        required: true
        type: string
      auth0_domain_noncustom:
        required: true
        type: string
      auth0_third_party_connection_name:
        required: true
        type: string
      react_app_tpp_auth0_client_id:
        required: true
        type: string
      auth0_risk_smart_rest_api_client_id:
        required: true
        type: string
      react_app_auth0_client_id:
        required: true
        type: string
      auth0_risk_smart_circle_client_id:
        required: false
        type: string
        default: ''
      bedrock_guardrail_identifier:
        required: true
        type: string
      bedrock_guardrail_version:
        required: true
        type: string
      diff_only:
        required: false
        type: boolean
        default: false
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true
      AWS_DEPLOY_ROLE:
        required: true
      HYBISCUS_API_KEY:
        required: false
jobs:
  RestApiDeploy:
    name: ${{ inputs.region}} - Deploy - REST API / SST
    runs-on:
      - ${{ inputs.runner_label }}
      - ${{ github.run_id }}-${{ github.run_attempt }}-RestApiDeploy
    environment: ${{ inputs.env }}
    permissions:
        actions: write
        contents: read
        id-token: write
        packages: read
    steps:
      - name: Setup Turbo cache
        uses: rharkor/caching-for-turbo@d124d2921c97c169010f6a7a624a36e9831472e1 # v 1.8

      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
        with:
          version: 10.28.2

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Configure pnpm for GitHub Packages
        run: |
          pnpm config set @risk-smart:registry https://npm.pkg.github.com
          pnpm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Start API containers
        run: docker compose up graphql-engine postgres --detach
        working-directory: api-stack

      - name: Wait for API
        timeout-minutes: 10
        run: bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:8080/v1/version)" != "200" ]]; do sleep 1; done'

      - name: Apply Hasura migrations
        run: pnpm run hasura-migrate:for-type-gen

      - name: Generate GraphQL types
        run: pnpm run generate-graphql

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ inputs.region }}

      - name: Set sentry release
        id: releaseid
        run: echo "sentry_release=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Install PostgreSQL dependencies
        run: sudo apt update && sudo apt-get install -y --fix-missing libpq-dev

      - name: SST ${{ inputs.diff_only && 'Diff' || 'Deploy' }}
        env:
          SENTRY_RELEASE: ${{steps.releaseid.outputs.sentry_release}}
          HASURA_ENDPOINT: https://${{ inputs.domain_prefix }}${{ vars.STAGE }}-${{ inputs.app_or_risksmart_app }}-api.${{ vars.AWS_ACCOUNT_ID }}.risksmart.link
          PDP_ENDPOINT: https://permissions-api-internal.${{ vars.STAGE }}.risksmart.link
          HASURA_TENANT_ENDPOINT: https://${{ inputs.domain_prefix }}${{ vars.STAGE }}-${{ inputs.app_or_risksmart_app }}-api-tenant.${{ vars.AWS_ACCOUNT_ID }}.risksmart.link
          AUTH0_DOMAIN: ${{ inputs.react_app_auth0_domain }}
          AUTH0_DOMAIN_NONCUSTOM: ${{ inputs.auth0_domain_noncustom }}
          AUTH0_API_REST_AUDIENCE: https://${{ inputs.domain_prefix }}${{ vars.STAGE }}-${{ inputs.app_or_risksmart_app }}-api.${{ vars.AWS_ACCOUNT_ID }}.risksmart.link
          AUTH0_API_INTEGRATIONS_AUDIENCE: https://${{ inputs.domain_prefix }}${{ vars.STAGE }}-int.${{ vars.AWS_ACCOUNT_ID }}.risksmart.link:8085
          SLACK_CLIENT_ID: ${{ vars.SLACK_CLIENT_ID }}
          AUTH0_MANAGEMENT_CLIENT_ID: ${{ vars.AUTH0_MANAGEMENT_CLIENT_ID }}
          AUTH0_THIRD_PARTY_CONNECTION_NAME: ${{ inputs.auth0_third_party_connection_name }}
          AUTH0_THIRD_PARTY_CLIENT_ID: ${{ inputs.react_app_tpp_auth0_client_id }}
          AUTH0_RISK_SMART_REST_API_CLIENT_ID: ${{ inputs.auth0_risk_smart_rest_api_client_id }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ inputs.react_app_auth0_client_id }}
          AUTH0_RISK_SMART_CIRCLE_CLIENT_ID: ${{ inputs.auth0_risk_smart_circle_client_id }}
          SCIM_INTERNAL_API_URL: https://${{ inputs.domain_prefix }}scim-api-internal.${{ vars.STAGE }}.risksmart.link
          SST_PRINT_LOGS: 1
          HYBISCUS_API_KEY: ${{ secrets.HYBISCUS_API_KEY }}
          HYBISCUS_API_URL: https://${{ vars.STAGE }}-${{ inputs.app_or_risksmart_app }}-tenant.${{ vars.AWS_ACCOUNT_ID }}.risksmart.link/hybiscus/api/v1/async
          WEB_APP_URL: https://${{ inputs.domain_prefix }}${{ vars.STAGE }}.risksmart.link
          IS_RISKSMART_REGION: ${{ inputs.is_risksmart_region }}
          DOMAIN_NAME_PREFIX: ${{ inputs.domain_prefix }}
          RESOURCE_PREFIX: ${{ inputs.resource_prefix }}
          AWS_REGION: ${{ inputs.region }}
          BEDROCK_GUARDRAIL_IDENTIFIER: ${{ inputs.bedrock_guardrail_identifier }}
          BEDROCK_GUARDRAIL_VERSION: ${{ inputs.bedrock_guardrail_version }}
        run: |
          if [ "${{ inputs.diff_only }}" = "true" ]; then
            pnpm run sst:diff --stage ${{ vars.SST_STAGE }} --region ${{ inputs.region }}
          else
            pnpm run sst:deploy --stage ${{ vars.SST_STAGE }} --region ${{ inputs.region }}
          fi

      - name: Deploy lambda source maps
        if: ${{ inputs.diff_only != true }}
        env:
          SENTRY_LOG_LEVEL: debug
          SENTRY_RELEASE: ${{steps.releaseid.outputs.sentry_release}}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: pnpm dlx @sentry/cli@2.39.1 releases --org risksmart --project risksmart-lambda-node files "$SENTRY_RELEASE" upload-sourcemaps .build/sourcemaps
