name: Template / Hasura Migrate

permissions:
  actions: write
  contents: read
  id-token: write
  packages: read

on:
  workflow_call:
    inputs:
      runner_label:
        required: false
        type: string
        default: "sprinters:aws:eu-west-2:ubuntu-latest:m7i-flex.large:spot=false"
      env:
        required: true
        type: string
      enable_turbo_cache:
        required: false
        type: string
        default: "false"
      aws_region:
        type: string
        default: "eu-west-2"
      domain_prefix:
        required: true
        type: string
      matrix:
        required: true
        type: string
      secret_name:
        required: false
        type: string
        default: ""
      app_or_risksmart_app:
        required: false
        type: string
        default: ""
      hasura_version:
        required: false
        type: string
        default: "v2.48.11"
      max_parallel:
        required: false
        type: number
        default: 5
        description: "Maximum number of matrix jobs to run in parallel (default 5)"

jobs:
  HasuraMigration-Tenant:
    name: Hasura Migration (${{ matrix.region }})
    runs-on:
      - ${{ inputs.runner_label }}
      - ${{ github.run_id }}-${{ github.run_attempt }}-HasuraMigration-${{ strategy.job-index }}
    environment:
      name: ${{ inputs.env }}
    strategy:
      max-parallel: ${{ inputs.max_parallel }}
      matrix: ${{ fromJson(inputs.matrix) }}
    steps:
      - name: Setup Turbo cache
        uses: rharkor/caching-for-turbo@d124d2921c97c169010f6a7a624a36e9831472e1 # v 1.8

      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
        with:
          version: 10.28.2

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"

      - name: Configure pnpm for GitHub Packages
        run: |
          pnpm config set @risk-smart:registry https://npm.pkg.github.com
          pnpm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Apply Hasura migrations
        uses: smplrspace/hasura-action@8306467475db70cba2c10da11ea61b435dbf2010 # v3.2 # use a tagged version instead of master
        with:
          args: migrate apply --all-databases
        env:
          HASURA_ENDPOINT: https://${{ inputs.domain_prefix }}${{ vars.STAGE }}-${{ inputs.app_or_risksmart_app }}-api-tenant.${{ vars.AWS_ACCOUNT_ID }}.risksmart.link/${{ matrix.tenantKey }}/
          # This should be exported by the AWS CDK but for now we add it manually
          HASURA_ADMIN_SECRET: ${{ secrets[inputs.secret_name] }}
          HASURA_WORKDIR: api-stack/hasura # replace this by your own path if needed
          HASURA_ENGINE_VERSION: ${{ inputs.hasura_version }} # replace this by the version you need, remove to use stable

      - name: Apply Hasura metadata
        uses: smplrspace/hasura-action@8306467475db70cba2c10da11ea61b435dbf2010 # v3.2 # use a tagged version instead of master
        with:
          args: metadata apply
        env:
          HASURA_ENDPOINT: https://${{ inputs.domain_prefix }}${{ vars.STAGE }}-${{ inputs.app_or_risksmart_app }}-api-tenant.${{ vars.AWS_ACCOUNT_ID }}.risksmart.link/${{ matrix.tenantKey }}/
          # This should be exported by the AWS CDK but for now we add it manually
          HASURA_ADMIN_SECRET: ${{ secrets[inputs.secret_name] }}
          HASURA_WORKDIR: api-stack/hasura # replace this by your own path if needed
          HASURA_ENGINE_VERSION: ${{ inputs.hasura_version }} # replace this by the version you need, remove to use stable
      # - name: Apply hasura seeds
      #   uses: smplrspace/hasura-action@430e0a2a4992a636425d407014d55a1691e1967d # v3.0 # use a tagged version instead of master
      #   with:
      #     args: seed apply --all-databases
      #   env:
      #     HASURA_ENDPOINT: https://${{ inputs.domain_prefix }}${{ vars.STAGE }}-${{ inputs.app_or_risksmart_app }}-api-tenant.${{ vars.AWS_ACCOUNT_ID }}.risksmart.link/${{ matrix.tenantKey }}/
      #     # This should be exported by the AWS CDK but for now we add it manually
      #     HASURA_ADMIN_SECRET: ${{ secrets[inputs.secret_name] }}
      #     HASURA_WORKDIR: api-stack/hasura # replace this by your own path if needed
      #     HASURA_ENGINE_VERSION: ${{ inputs.hasura_version }} # replace this by the version you need, remove to use stable

      - name: Apply hasura reload
        uses: smplrspace/hasura-action@8306467475db70cba2c10da11ea61b435dbf2010 # v3.2 # use a tagged version instead of master
        with:
          args: metadata reload
        env:
          HASURA_ENDPOINT: https://${{ inputs.domain_prefix }}${{ vars.STAGE }}-${{ inputs.app_or_risksmart_app }}-api-tenant.${{ vars.AWS_ACCOUNT_ID }}.risksmart.link/${{ matrix.tenantKey }}/
          # This should be exported by the AWS CDK but for now we add it manually
          HASURA_ADMIN_SECRET: ${{ secrets[inputs.secret_name] }}
          HASURA_WORKDIR: api-stack/hasura # replace this by your own path if needed
          HASURA_ENGINE_VERSION: ${{ inputs.hasura_version }} # replace this by the version you need, remove to use stable
