name: Template / CDK Synth

# Used in pre-merge
# Runs `cdk synth` to generate CF templates, uses cdk-diff-action to post PR comments

permissions:
  actions: write
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      runner_label:
        required: false
        type: string
        default: 'sprinters:aws:eu-west-2:ubuntu-latest:m7i-flex.xlarge:spot=false'
      env:
        required: true
        type: string
      trpc_container_build:
        required: false
        type: string
        default: 'da99825'
      extapi_container_build:
        required: false
        type: string
        default: '0.0.3'
      extapi_config:
        required: false
        type: string
        default: ''
      tenant_deployer_container_build:
        required: false
        type: string
        default: '4ae496e'
      integrations_container_build:
        description: 'Integrations container semver tag (e.g., 1.0.0). Required.'
        required: true
        type: string
    secrets:
      HASURA_JWT_SECRET:
        required: true
      AWS_DEPLOY_ROLE:
        required: true
      TRPC_SENTRY_DSN:
        required: false
      REACT_APP_AUTH0_DOMAIN:
        required: false
jobs:
  Existing-Infra-Synth:
    name: Synth - Existing Infra
    runs-on:
      - ${{ inputs.runner_label }}
      - ${{ github.run_id }}-${{ github.run_attempt }}-Existing-Infra-Synth
    environment: ${{ inputs.env }}
    permissions:
        actions: write
        contents: read
        id-token: write
        pull-requests: write
        packages: read
    steps:
      - name: Setup Turbo cache
        uses: rharkor/caching-for-turbo@d124d2921c97c169010f6a7a624a36e9831472e1 # v 1.8

      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
        with:
          version: 10.28.2

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Configure pnpm for GitHub Packages
        run: |
          pnpm config set @risk-smart:registry https://npm.pkg.github.com
          pnpm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.14.2'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install AWS CLI
        run: |
          pip install awscli
          aws --version

      # - name: Download artifact
      #   uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
      #   with:
      #     name: integrations-build
      #     path: cdk-stack/lib/int

      - name: Set sentry release
        id: releaseid
        run: echo "sentry_release=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Synth
        env:
          STAGE: ${{ vars.STAGE }}
          BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
          APP_NAME: ${{ vars.APP_NAME }}
          TPP_APP_NAME: ${{ vars.TPP_APP_NAME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          HASURA_JWT_SECRET: ${{ secrets.HASURA_JWT_SECRET }}
          MULTI_TENANT_SNAPSHOT_NAME: ${{ vars.STAGE }}-risksmartapp-db-cluster-snapshot-build-${{github.run_number}}-${{github.run_attempt}}
          VPN_ENABLED: true
          TRPC_CONTAINER_BUILD: ${{ inputs.trpc_container_build }}
          TENANT_DEPLOYER_CONTAINER_BUILD: ${{ inputs.tenant_deployer_container_build }}
          SENTRY_RELEASE: ${{steps.releaseid.outputs.sentry_release}}
          EXTAPI_CONTAINER_BUILD: ${{ inputs.extapi_container_build }}
          EXTAPI_STACK_CONFIG: ${{ inputs.extapi_config }}
          INTEGRATIONS_CONTAINER_BUILD: ${{ inputs.integrations_container_build }}
          TRPC_SENTRY_DSN: ${{ secrets.TRPC_SENTRY_DSN }}
          AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN }}
          AUTH0_MANAGEMENT_CLIENT_ID: ${{ vars.AUTH0_MANAGEMENT_CLIENT_ID }}
          AUTH0_RISK_SMART_REST_API_CLIENT_ID: ${{ vars.AUTH0_RISK_SMART_REST_API_CLIENT_ID_UK }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ vars.REACT_APP_AUTH0_CLIENT_ID_UK }}
        run: |
          cd cdk-stack
          pnpm exec cdk synth --app "pnpm dlx ts-node --prefer-ts-exts ./bin/cdk-stack.ts"  '*'

      - name: Upload CDK artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: cdk
          path: /home/runner/work/**/cdk.out
          retention-days: 5

      - name: Diff
        uses: corymhall/cdk-diff-action@f6a58358690c94f79d5f9fa485a93a4cb5f67541
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cdkOutDir: cdk-stack/cdk.out
          failOnDestructiveChanges: false

  # US-1-Infra-Synth:
  #   name: Synth - US-1
  #   runs-on:
  #     - ${{ inputs.runner_label }}
  #     - ${{ github.run_id }}-${{ github.run_attempt }}-US-1-Infra-Synth
  #   environment: ${{ inputs.env }}
  #   permissions:
  #       actions: write
  #       contents: read
  #       id-token: write
  #       pull-requests: write
  #       packages: read
  #   steps:
  #     - uses: rharkor/caching-for-turbo@7736a1794b8d89776791d5a24f20c581479b671b # v 1.8
  #     - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
  #     - name: Setup pnpm
  #       uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
  #       with:
  #         version: 10.27.0
  #     - name: Setup node
  #       uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
  #       with:
  #         node-version: '20.19.4'
  #         cache: 'pnpm'
  #         registry-url: 'https://npm.pkg.github.com'
  #     - name: Configure pnpm for GitHub Packages
  #       run: |
  #         pnpm config set @risk-smart:registry https://npm.pkg.github.com
  #         pnpm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
  #     - name: Install dependencies
  #       run: pnpm install
  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
  #       with:
  #         python-version: '3.13.7'
  #     - name: Configure AWS credentials from account
  #       uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
  #       with:
  #         role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
  #         aws-region: ${{ vars.AWS_REGION_US1 }}
  #     - name: Install AWS CLI
  #       run: |
  #         pip install awscli
  #         aws --version
  #     - name: Download artifact
  #       uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5   # v4
  #       with:
  #         name: integrations-build
  #         path: cdk-stack/lib/int
  #     - name: Set sentry release
  #       id: releaseid
  #       run: echo "sentry_release=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  #     - name: Synth
  #       env:
  #         STAGE: ${{ vars.STAGE }}
  #         BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
  #         APP_NAME_FOR_RS_REGION: ${{ vars.APP_NAME_FOR_RS_REGION }}
  #         TPP_APP_NAME: ${{ vars.TPP_APP_NAME }}
  #         AWS_REGION: ${{ vars.AWS_REGION_US1 }}
  #         AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  #         HASURA_JWT_SECRET: ${{ secrets.HASURA_JWT_SECRET }}
  #         MULTI_TENANT_SNAPSHOT_NAME: US-1-${{ vars.STAGE }}-app-db-cluster-snapshot-build-${{github.run_number}}-${{github.run_attempt}}
  #         VPN_ENABLED: false
  #         RISKSMART_REGION: true
  #         RISKSMART_REGION_PREFIX: us
  #         RISKSMART_REGION_ID: US-1
  #         TRPC_CONTAINER_BUILD: ${{ inputs.trpc_container_build }}
  #         TENANT_DEPLOYER_CONTAINER_BUILD: ${{ inputs.tenant_deployer_container_build }}
  #         SENTRY_RELEASE: ${{steps.releaseid.outputs.sentry_release}}
  #         EXTAPI_CONTAINER_BUILD: ${{ inputs.extapi_container_build }}
  #         EXTAPI_STACK_CONFIG: ${{ inputs.extapi_config }}
  #         TRPC_SENTRY_DSN: ${{ secrets.TRPC_SENTRY_DSN }}
  #       run: |
  #         cd cdk-stack
  #         pnpm exec cdk synth --app "pnpm dlx ts-node --prefer-ts-exts ./bin/cdk-stack.ts"  '*'
  #     - name: Diff
  #       uses: corymhall/cdk-diff-action@f6a58358690c94f79d5f9fa485a93a4cb5f67541
  #       with:
  #         githubToken: ${{ secrets.GITHUB_TOKEN }}
  #         cdkOutDir: cdk-stack/cdk.out
  #         failOnDestructiveChanges: false

  # UAE-1-Infra-Synth:
  #   name: Synth - UAE-1
  #   runs-on:
  #     - ${{ inputs.runner_label }}
  #     - ${{ github.run_id }}-${{ github.run_attempt }}-UAE-1-Infra-Synth
  #   environment: ${{ inputs.env }}
  #   permissions:
  #       actions: write
  #       contents: read
  #       id-token: write
  #       pull-requests: write
  #       packages: read
  #   steps:
  #     - uses: rharkor/caching-for-turbo@7736a1794b8d89776791d5a24f20c581479b671b # v 1.8
  #     - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
  #     - name: Setup pnpm
  #       uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
  #       with:
  #         version: 10.27.0
  #     - name: Setup node
  #       uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
  #       with:
  #         node-version: '20.19.4'
  #         cache: 'pnpm'
  #         registry-url: 'https://npm.pkg.github.com'
  #     - name: Configure pnpm for GitHub Packages
  #       run: |
  #         pnpm config set @risk-smart:registry https://npm.pkg.github.com
  #         pnpm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
  #     - name: Install dependencies
  #       run: pnpm install
  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
  #       with:
  #         python-version: '3.13.7'
  #     - name: Configure AWS credentials from account
  #       uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
  #       with:
  #         role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
  #         aws-region: ${{ vars.AWS_REGION_UAE1 }}
  #     - name: Install AWS CLI
  #       run: |
  #         pip install awscli
  #         aws --version
  #     - name: Download artifact
  #       uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5   # v4
  #       with:
  #         name: integrations-build
  #         path: cdk-stack/lib/int
  #     - name: Set sentry release
  #       id: releaseid
  #       run: echo "sentry_release=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  #     - name: Synth
  #       env:
  #         STAGE: ${{ vars.STAGE }}
  #         BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
  #         APP_NAME_FOR_RS_REGION: ${{ vars.APP_NAME_FOR_RS_REGION }}
  #         TPP_APP_NAME: ${{ vars.TPP_APP_NAME }}
  #         AWS_REGION: ${{ vars.AWS_REGION_UAE1 }}
  #         AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  #         HASURA_JWT_SECRET: ${{ secrets.HASURA_JWT_SECRET }}
  #         MULTI_TENANT_SNAPSHOT_NAME: US-1-${{ vars.STAGE }}-app-db-cluster-snapshot-build-${{github.run_number}}-${{github.run_attempt}}
  #         VPN_ENABLED: false
  #         RISKSMART_REGION: true
  #         RISKSMART_REGION_PREFIX: uae
  #         RISKSMART_REGION_ID: UAE-1
  #         TRPC_CONTAINER_BUILD: ${{ inputs.trpc_container_build }}
  #         TENANT_DEPLOYER_CONTAINER_BUILD: ${{ inputs.tenant_deployer_container_build }}
  #         EXTAPI_CONTAINER_BUILD: ${{ inputs.extapi_container_build }}
  #         EXTAPI_STACK_CONFIG: ${{ inputs.extapi_config }}
  #         TRPC_SENTRY_DSN: ${{ secrets.TRPC_SENTRY_DSN }}
  #         SENTRY_RELEASE: ${{steps.releaseid.outputs.sentry_release}}
  #       run: |
  #         cd cdk-stack
  #         pnpm exec cdk synth --app "pnpm dlx ts-node --prefer-ts-exts ./bin/cdk-stack.ts"  '*'
  #     - name: Diff
  #       uses: corymhall/cdk-diff-action@f6a58358690c94f79d5f9fa485a93a4cb5f67541
  #       with:
  #         githubToken: ${{ secrets.GITHUB_TOKEN }}
  #         cdkOutDir: cdk-stack/cdk.out
  #         failOnDestructiveChanges: false
