name: Auto / Tofu Workspaces Dev Cloud

on:
  pull_request:
    paths:
      - 'infrastructure/aws/workspaces/app-environments/**'
      - 'packages/external-api/package.json'
      - '.github/workflows/auto-tofu-workspaces-dev-cloud.yml'
  push:
    paths:
      - 'infrastructure/aws/workspaces/app-environments/**'
      - 'packages/external-api/package.json'
      - '.github/workflows/auto-tofu-workspaces-dev-cloud.yml'
    branches:
      - main

jobs:
  tofu-plan-eu-west-2:
    name:  eu-west-2 - dev-cloud Account - OpenTofu Plan (Main)
    uses: ./.github/workflows/_template-tofu-plan-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:eu-west-2:ubuntu-latest:m7i-flex.large:spot=false'
      env: dev-cloud
      aws_region: eu-west-2
      account: dev-cloud
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'dev-cloud-eu-west-2.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::640196420962:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-apply-eu-west-2:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: eu-west-2 - dev-cloud Account - OpenTofu Apply (Main)
    uses: ./.github/workflows/_template-tofu-apply-workspaces.yml
    needs:
      - tofu-plan-eu-west-2
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:eu-west-2:ubuntu-latest:m7i-flex.large:spot=false'
      env: dev-cloud
      aws_region: eu-west-2
      account: dev-cloud
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'dev-cloud-eu-west-2.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::640196420962:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit
  
  # Commented out the below plan & apply while me-central-1 region is under drone attack. 
  # Can re-instate when its back up and running 
  #
  # tofu-plan-me-central-1:
  #   name:  me-central-1 - dev-cloud Account - OpenTofu Plan (Main)
  #   uses: ./.github/workflows/_template-tofu-plan-workspaces.yml
  #   permissions:
  #     pull-requests: write
  #     actions: write
  #     contents: read
  #     id-token: write
  #   with:
  #     runner_label: 'sprinters:aws:me-central-1:ubuntu-latest:m7i.large:spot=false'
  #     env: dev-cloud
  #     aws_region: me-central-1
  #     account: dev-cloud
  #     tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
  #     tf_vars_file: 'dev-cloud-me-central-1.tfvars'
  #     uses_workspaces: true
  #     deploy_role: 'arn:aws:iam::640196420962:role/RiskSmart-GitHub-Deploy-Role'
  #   secrets: inherit

  # tofu-apply-me-central-1:
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   name: me-central-1 - dev-cloud Account - OpenTofu Apply (Main)
  #   uses: ./.github/workflows/_template-tofu-apply-workspaces.yml
  #   needs:
  #     - tofu-plan-me-central-1
  #   permissions:
  #     pull-requests: write
  #     actions: write
  #     contents: read
  #     id-token: write
  #   with:
  #     runner_label: 'sprinters:aws:me-central-1:ubuntu-latest:m7i.large:spot=false'
  #     env: dev-cloud
  #     aws_region: me-central-1
  #     account: dev-cloud
  #     tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
  #     tf_vars_file: 'dev-cloud-me-central-1.tfvars'
  #     uses_workspaces: true
  #     deploy_role: 'arn:aws:iam::640196420962:role/RiskSmart-GitHub-Deploy-Role'
  #   secrets: inherit

  tofu-plan-ca-central-1:
    name:  ca-central-1 - dev-cloud Account - OpenTofu Plan (Main)
    uses: ./.github/workflows/_template-tofu-plan-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:ca-central-1:ubuntu-latest:m7i-flex.large:spot=false'
      env: dev-cloud
      aws_region: ca-central-1
      account: dev-cloud
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'dev-cloud-ca-central-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::640196420962:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-apply-ca-central-1:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: ca-central-1 - dev-cloud Account - OpenTofu Apply (Main)
    uses: ./.github/workflows/_template-tofu-apply-workspaces.yml
    needs:
      - tofu-plan-ca-central-1
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:ca-central-1:ubuntu-latest:m7i-flex.large:spot=false'
      env: dev-cloud
      aws_region: ca-central-1
      account: dev-cloud
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'dev-cloud-ca-central-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::640196420962:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-plan-us-east-1:
    name:  us-east-1 - dev-cloud Account - OpenTofu Plan (Main)
    uses: ./.github/workflows/_template-tofu-plan-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:us-east-1:ubuntu-latest:m7i-flex.large:spot=false'
      env: dev-cloud
      aws_region: us-east-1
      account: dev-cloud
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'dev-cloud-us-east-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::640196420962:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-apply-us-east-1:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: us-east-1 - dev-cloud Account - OpenTofu Apply (Main)
    uses: ./.github/workflows/_template-tofu-apply-workspaces.yml
    needs:
      - tofu-plan-us-east-1
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:us-east-1:ubuntu-latest:m7i-flex.large:spot=false'
      env: dev-cloud
      aws_region: us-east-1
      account: dev-cloud
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'dev-cloud-us-east-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::640196420962:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit
