name: Manual / Tofu Workspaces Staging

on:
  workflow_dispatch:
    inputs:
      deploy_uk:
        description: 'Deploy to UK (eu-west-2)'
        type: boolean
        default: true
      deploy_us:
        description: 'Deploy to US (us-east-1)'
        type: boolean
        default: true
      deploy_uae:
        description: 'Deploy to UAE (me-central-1)'
        type: boolean
        default: true
      deploy_ca:
        description: 'Deploy to CA (ca-central-1)'
        type: boolean
        default: true
      action:
        description: 'Tofu action to perform (plan only, or plan and apply)'
        required: true
        type: choice
        default: 'plan'
        options:
          - plan
          - plan-and-apply

permissions:
  contents: read
  packages: read

jobs:
  # PLAN JOBS
  tofu-plan-eu-west-2:
    name: eu-west-2 - Staging Account - OpenTofu Plan
    if: ${{ inputs.deploy_uk }}
    uses: ./.github/workflows/_template-tofu-plan-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:eu-west-2:ubuntu-latest:m7i-flex.large:spot=false'
      env: staging
      aws_region: eu-west-2
      account: staging
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'staging-eu-west-2.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::629531182017:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-plan-me-central-1:
    name: me-central-1 - Staging Account - OpenTofu Plan
    if: ${{ inputs.deploy_uae }}
    uses: ./.github/workflows/_template-tofu-plan-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:me-central-1:ubuntu-latest:m7i.large:spot=false'
      env: staging
      aws_region: me-central-1
      account: staging
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'staging-me-central-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::629531182017:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-plan-us-east-1:
    name: us-east-1 - Staging Account - OpenTofu Plan
    if: ${{ inputs.deploy_us }}
    uses: ./.github/workflows/_template-tofu-plan-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:us-east-1:ubuntu-latest:m7i-flex.large:spot=false'
      env: staging
      aws_region: us-east-1
      account: staging
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'staging-us-east-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::629531182017:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-plan-ca-central-1:
    name: ca-central-1 - Staging Account - OpenTofu Plan
    if: ${{ inputs.deploy_ca }}
    uses: ./.github/workflows/_template-tofu-plan-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:ca-central-1:ubuntu-latest:m7i-flex.large:spot=false'
      env: staging
      aws_region: ca-central-1
      account: staging
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'staging-ca-central-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::629531182017:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  # APPLY JOBS
  tofu-apply-eu-west-2:
    name: eu-west-2 - Staging Account - OpenTofu Apply
    needs: [tofu-plan-eu-west-2]
    if: |
      inputs.deploy_uk &&
      !cancelled() &&
      (needs.tofu-plan-eu-west-2.result == 'success' || needs.tofu-plan-eu-west-2.result == 'skipped') &&
      inputs.action == 'plan-and-apply'
    uses: ./.github/workflows/_template-tofu-apply-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:eu-west-2:ubuntu-latest:m7i-flex.large:spot=false'
      env: staging
      aws_region: eu-west-2
      account: staging
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'staging-eu-west-2.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::629531182017:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-apply-me-central-1:
    name: me-central-1 - Staging Account - OpenTofu Apply
    needs: [tofu-plan-me-central-1]
    if: |
      inputs.deploy_uae &&
      !cancelled() &&
      (needs.tofu-plan-me-central-1.result == 'success' || needs.tofu-plan-me-central-1.result == 'skipped') &&
      inputs.action == 'plan-and-apply'
    uses: ./.github/workflows/_template-tofu-apply-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:me-central-1:ubuntu-latest:m7i.large:spot=false'
      env: staging
      aws_region: me-central-1
      account: staging
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'staging-me-central-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::629531182017:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-apply-us-east-1:
    name: us-east-1 - Staging Account - OpenTofu Apply
    needs: [tofu-plan-us-east-1]
    if: |
      inputs.deploy_us &&
      !cancelled() &&
      (needs.tofu-plan-us-east-1.result == 'success' || needs.tofu-plan-us-east-1.result == 'skipped') &&
      inputs.action == 'plan-and-apply'
    uses: ./.github/workflows/_template-tofu-apply-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:us-east-1:ubuntu-latest:m7i-flex.large:spot=false'
      env: staging
      aws_region: us-east-1
      account: staging
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'staging-us-east-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::629531182017:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit

  tofu-apply-ca-central-1:
    name: ca-central-1 - Staging Account - OpenTofu Apply
    needs: [tofu-plan-ca-central-1]
    if: |
      inputs.deploy_ca &&
      !cancelled() &&
      (needs.tofu-plan-ca-central-1.result == 'success' || needs.tofu-plan-ca-central-1.result == 'skipped') &&
      inputs.action == 'plan-and-apply'
    uses: ./.github/workflows/_template-tofu-apply-workspaces.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
    with:
      runner_label: 'sprinters:aws:ca-central-1:ubuntu-latest:m7i-flex.large:spot=false'
      env: staging
      aws_region: ca-central-1
      account: staging
      tf_actions_working_dir: 'infrastructure/aws/workspaces/app-environments/'
      tf_vars_file: 'staging-ca-central-1.tfvars'
      uses_workspaces: true
      deploy_role: 'arn:aws:iam::629531182017:role/RiskSmart-GitHub-Deploy-Role'
    secrets: inherit
