name: Manual / TRPC Build

permissions:
  pull-requests: write
  actions: write
  contents: read
  id-token: write
  packages: read

on: [workflow_dispatch]

jobs:
  TRPCBuild:
    name: TRPC / Build
    uses: ./.github/workflows/_template-container-build-push.yml
    permissions:
      pull-requests: write
      actions: write
      contents: read
      id-token: write
      packages: read
    with:
      env: ci
      enable_turbo_cache: true
      container_name: "trpc-api"
      container_dockerfile: "packages/trpc/Dockerfile"
      path_to_artifact: "packages/trpc"
      ecr_repo_name: "risksmart/trpc-api"
      aws_region: "eu-west-2"
    secrets: inherit
