triggers:
  post-login:
    - action_name: DocsAuth
      display_name: DocsAuth
    - action_name: Create Risksmart User
      display_name: Create Risksmart User
  credentials-exchange:
    - action_name: Add M2M Claims
      display_name: Add M2M Claims
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    enabled_clients:
      - auth0-deploy-cli
      - RiskSmart
      - RiskSmart Rest API
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      import_mode: false
      customScripts:
        change_password: ./databases/Username-Password-Authentication/change_password.js
        create: ./databases/Username-Password-Authentication/create.js
        delete: ./databases/Username-Password-Authentication/delete.js
        get_user: ./databases/Username-Password-Authentication/get_user.js
        login: ./databases/Username-Password-Authentication/login.js
        verify: ./databases/Username-Password-Authentication/verify.js
      disable_signup: true
      passwordPolicy: good
      password_history:
        size: 5
        enable: true
      strategy_version: 2
      password_dictionary:
        enable: true
        dictionary: []
      brute_force_protection: true
      password_no_personal_info:
        enable: true
      password_complexity_options:
        min_length: 8
      enabledDatabaseCustomization: false
    realms:
      - Username-Password-Authentication
  - name: Username-Password-ThirdParty
    strategy: auth0
    enabled_clients:
      - Third Party Portal
      - RiskSmart Rest API
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      import_mode: false
      customScripts:
        change_password: ./databases/Username-Password-Authentication/change_password.js
        create: ./databases/Username-Password-Authentication/create.js
        delete: ./databases/Username-Password-Authentication/delete.js
        get_user: ./databases/Username-Password-Authentication/get_user.js
        login: ./databases/Username-Password-Authentication/login.js
        verify: ./databases/Username-Password-Authentication/verify.js
      disable_signup: true
      passwordPolicy: good
      password_history:
        size: 5
        enable: true
      strategy_version: 2
      requires_username: true
      password_dictionary:
        enable: true
        dictionary: []
      brute_force_protection: true
      password_no_personal_info:
        enable: true
      password_complexity_options:
        min_length: 8
      enabledDatabaseCustomization: false
    realms:
      - Username-Password-ThirdParty
clients:
  - name: RiskSmart
    allowed_clients: []
    allowed_logout_urls: @@APP_ALLOWED_LOGOUT@@
    app_type: spa
    callbacks: @@APP_CALLBACKS@@
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - refresh_token
    initiate_login_uri: ##APP_LOGIN_URL##
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 600
      secret_encoded: false
    logo_uri: >-
      ##RISK_SMART_AUTH_LOGO##
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    organization_require_behavior: post_login_prompt
    organization_usage: require
    refresh_token:
      expiration_type: expiring
      leeway: 5
      token_lifetime: 86400
      idle_token_lifetime: 14400
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins: @@APP_WEB_ORIGINS@@
  - name: Third Party Portal
    allowed_clients: []
    allowed_logout_urls: @@THIRD_PARTY_PORTAL_ALLOWED_LOGOUT@@
    app_type: spa
    callbacks: @@THIRD_PARTY_PORTAL_CALLBACKS@@
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - refresh_token
    initiate_login_uri: ##THIRD_PARTY_PORTAL_LOGIN_URL##
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 600
      secret_encoded: false
    logo_uri: >-
      ##RISK_SMART_AUTH_LOGO##
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    organization_require_behavior: post_login_prompt
    organization_usage: require
    refresh_token:
      expiration_type: expiring
      leeway: 5
      token_lifetime: 86400
      idle_token_lifetime: 14400
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins: @@THIRD_PARTY_PORTAL_WEB_ORIGINS@@
  - name: RiskSmart-Integrations
    app_type: non_interactive
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
    client_metadata:
      org_id: org_Qshp7tYsxxAWwhVa
      tenant: MultiTenant
  - name: auth0-deploy-cli
    app_type: non_interactive
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: RiskSmart Rest API
    app_type: non_interactive
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
