INSERT INTO risksmart.role_access (
        "RoleKey",
        "ObjectType",
        "ContributorType",
        "AccessType"
    )
VALUES (
        'RiskManager',
        'tag_type',
        'any',
        'insert'
    ),
    (
        'RiskManager',
        'tag_type',
        'any',
        'delete'
    ),
    (
        'RiskManager',
        'department_type',
        'any',
        'insert'
    ),
    (
        'RiskManager',
        'department_type',
        'any',
        'delete'
    ),
    (
        'CustomerSupport',
        'tag_type',
        'any',
        'insert'
    ),
    (
        'CustomerSupport',
        'tag_type',
        'any',
        'delete'
    ),
    (
        'CustomerSupport',
        'department_type',
        'any',
        'insert'
    ),
    (
        'CustomerSupport',
        'department_type',
        'any',
        'delete'
    );