--Granular permissions for settings tabs
INSERT INTO risksmart.parent_type ("Value", "Comment")
VALUES ('settings_users', 'User Settings'),
    ('settings_user_groups', 'User Group Settings'),
    ('settings_tags', 'Tag Settings'),
    ('settings_departments', 'Department Settings'),
    ('settings_audit', 'Audit Settings'),
    ('settings_approvals', 'Approvals Settings');

INSERT INTO risksmart.role_access (
        "RoleKey",
        "ObjectType",
        "ContributorType",
        "AccessType"
    )
VALUES (
        'CustomerSupport',
        'settings_users',
        'any',
        'read'
    ),
    (
        'CustomerSupport',
        'settings_users',
        'any',
        'update'
    ),
    (
        'CustomerSupport',
        'settings_users',
        'any',
        'delete'
    ),
    (
        'CustomerSupport',
        'settings_users',
        'any',
        'insert'
    ),
    (
        'CustomerSupport',
        'settings_user_groups',
        'any',
        'read'
    ),
    (
        'CustomerSupport',
        'settings_user_groups',
        'any',
        'update'
    ),
    (
        'CustomerSupport',
        'settings_user_groups',
        'any',
        'delete'
    ),
    (
        'CustomerSupport',
        'settings_user_groups',
        'any',
        'insert'
    ),
    (
        'CustomerSupport',
        'settings_tags',
        'any',
        'read'
    ),
    (
        'CustomerSupport',
        'settings_tags',
        'any',
        'update'
    ),
    (
        'CustomerSupport',
        'settings_tags',
        'any',
        'delete'
    ),
    (
        'CustomerSupport',
        'settings_tags',
        'any',
        'insert'
    ),
    (
        'CustomerSupport',
        'settings_departments',
        'any',
        'read'
    ),
    (
        'CustomerSupport',
        'settings_departments',
        'any',
        'update'
    ),
    (
        'CustomerSupport',
        'settings_departments',
        'any',
        'delete'
    ),
    (
        'CustomerSupport',
        'settings_departments',
        'any',
        'insert'
    ),
    (
        'CustomerSupport',
        'settings_audit',
        'any',
        'read'
    ),
    (
        'CustomerSupport',
        'settings_audit',
        'any',
        'update'
    ),
    (
        'CustomerSupport',
        'settings_audit',
        'any',
        'delete'
    ),
    (
        'CustomerSupport',
        'settings_audit',
        'any',
        'insert'
    ),
    (
        'CustomerSupport',
        'settings_approvals',
        'any',
        'read'
    ),
    (
        'CustomerSupport',
        'settings_approvals',
        'any',
        'update'
    ),
    (
        'CustomerSupport',
        'settings_approvals',
        'any',
        'delete'
    ),
    (
        'CustomerSupport',
        'settings_approvals',
        'any',
        'insert'
    ),
    (
        'RiskManager',
        'settings_users',
        'any',
        'read'
    ),
    (
        'RiskManager',
        'settings_users',
        'any',
        'update'
    ),
    (
        'RiskManager',
        'settings_users',
        'any',
        'delete'
    ),
    (
        'RiskManager',
        'settings_users',
        'any',
        'insert'
    ),
    (
        'RiskManager',
        'settings_user_groups',
        'any',
        'read'
    ),
    (
        'RiskManager',
        'settings_user_groups',
        'any',
        'update'
    ),
    (
        'RiskManager',
        'settings_user_groups',
        'any',
        'delete'
    ),
    (
        'RiskManager',
        'settings_user_groups',
        'any',
        'insert'
    ),
    (
        'RiskManager',
        'settings_tags',
        'any',
        'read'
    ),
    (
        'RiskManager',
        'settings_tags',
        'any',
        'update'
    ),
    (
        'RiskManager',
        'settings_tags',
        'any',
        'delete'
    ),
    (
        'RiskManager',
        'settings_tags',
        'any',
        'insert'
    ),
    (
        'RiskManager',
        'settings_departments',
        'any',
        'read'
    ),
    (
        'RiskManager',
        'settings_departments',
        'any',
        'update'
    ),
    (
        'RiskManager',
        'settings_departments',
        'any',
        'delete'
    ),
    (
        'RiskManager',
        'settings_departments',
        'any',
        'insert'
    ),
    (
        'RiskManager',
        'settings_audit',
        'any',
        'read'
    ),
    (
        'RiskManager',
        'settings_audit',
        'any',
        'update'
    ),
    (
        'RiskManager',
        'settings_audit',
        'any',
        'delete'
    ),
    (
        'RiskManager',
        'settings_audit',
        'any',
        'insert'
    ),
    (
        'RiskManager',
        'settings_approvals',
        'any',
        'read'
    ),
    (
        'RiskManager',
        'settings_approvals',
        'any',
        'update'
    ),
    (
        'RiskManager',
        'settings_approvals',
        'any',
        'delete'
    ),
    (
        'RiskManager',
        'settings_approvals',
        'any',
        'insert'
    );