AWSTemplateFormatVersion: '2010-09-09'
Description: 'Tofu Bootstrap Resources V2'
Parameters:
  AccountName:
    Type: String
    Default: ''
    Description: The account name for the stack

  AccountId:
    Type: String
    Default: ''
    Description: The AWS account ID

  Region:
    Type: String
    Default: ''
    Description: The AWS region

Resources:
  S3StateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AccountName}-${Region}-risksmart-terraform-state'
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 1000
            NoncurrentVersionExpirationInDays: 30
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: alias/aws/s3
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${AccountName}-${Region}-risksmart-terraform-state'

  DynamoDBLockTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${AccountName}-${Region}-risksmart-terraform-lock'
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification: 
        SSEEnabled: true
        SSEType: KMS
      Tags:
        - Key: Name
          Value: !Sub '${AccountName}-${Region}-risksmart-terraform-locks'
