drop function risksmart.get_document_ancestor_contributors;

drop function risksmart.get_action_ancestor_contributors;

drop function risksmart.get_assessment_ancestor_contributors;

drop function risksmart.get_control_ancestor_contributors;

drop function risksmart.get_control_group_ancestor_contributors;

drop function risksmart.get_indicator_ancestor_contributors;

drop function risksmart.get_issue_ancestor_contributors;

drop function risksmart.get_node_ancestor_contributors;

drop function risksmart.get_obligation_ancestor_contributors;

drop function risksmart.get_risk_ancestor_contributors;

drop function risksmart.get_ancestor_contributors;

drop function risksmart.get_change_request_parent_ancestor_contributors;