INSERT INTO risksmart.role_access (
    "RoleKey",
    "ObjectType",
    "ContributorType",
    "AccessType"
)
VALUES (
           'ReadOnly',
           'colour_palette',
           'any',
           'read'
       ),
       (
           'Standard',
           'colour_palette',
           'any',
           'read'
       ),
       (
           'InternalAudit',
           'colour_palette',
           'any',
           'read'
       ),
       (
           'CustomerSupport',
           'colour_palette',
           'any',
           'read'
       ),
       (
           'CustomerSupport',
           'colour_palette',
           'any',
           'insert'
       ),
       (
           'CustomerSupport',
           'colour_palette',
           'any',
           'update'
       ),
       (
           'CustomerSupport',
           'colour_palette',
           'any',
           'delete'
       ),
       (
           'StandardEnhanced',
           'colour_palette',
           'any',
           'read'
       ),
       (
           'Public',
           'colour_palette',
           'any',
           'read'
       );