INSERT INTO risksmart.role_access (
        "RoleKey",
        "ObjectType",
        "ContributorType",
        "AccessType"
    )
VALUES -- Read
    ('Standard', 'third_party', 'owner', 'read'),
    ('Standard', 'third_party', 'contributor', 'read'),
    (
        'StandardEnhanced',
        'third_party',
        'owner',
        'read'
    ),
    (
        'StandardEnhanced',
        'third_party',
        'contributor',
        'read'
    ),
    -- Update
    ('Standard', 'third_party', 'owner', 'update'),
    (
        'Standard',
        'third_party',
        'contributor',
        'update'
    ),
    (
        'StandardEnhanced',
        'third_party',
        'owner',
        'update'
    ),
    (
        'StandardEnhanced',
        'third_party',
        'contributor',
        'update'
    ),
    (
        'InternalAudit',
        'third_party',
        'owner',
        'update'
    ),
    (
        'InternalAudit',
        'third_party',
        'contributor',
        'update'
    ),
    (
        'ReadOnly',
        'third_party',
        'contributor',
        'update'
    ),
    (
        'ReadOnly',
        'third_party',
        'owner',
        'update'
    ),
    -- Delete
    ('Standard', 'third_party', 'owner', 'delete'),
    (
        'StandardEnhanced',
        'third_party',
        'owner',
        'delete'
    ),
    (
        'ReadOnly',
        'third_party',
        'owner',
        'delete'
    ),
    (
        'InternalAudit',
        'third_party',
        'owner',
        'delete'
    );

--  Questionnaire template
INSERT INTO risksmart.role_access (
        "RoleKey",
        "ObjectType",
        "ContributorType",
        "AccessType"
    )
VALUES -- Read
    (
        'Standard',
        'questionnaire_template',
        'owner',
        'read'
    ),
    (
        'Standard',
        'questionnaire_template',
        'contributor',
        'read'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template',
        'owner',
        'read'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template',
        'contributor',
        'read'
    ),
    -- Update
    (
        'Standard',
        'questionnaire_template',
        'owner',
        'update'
    ),
    (
        'Standard',
        'questionnaire_template',
        'contributor',
        'update'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template',
        'owner',
        'update'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template',
        'contributor',
        'update'
    ),
    (
        'InternalAudit',
        'questionnaire_template',
        'owner',
        'update'
    ),
    (
        'InternalAudit',
        'questionnaire_template',
        'contributor',
        'update'
    ),
    (
        'ReadOnly',
        'questionnaire_template',
        'contributor',
        'update'
    ),
    (
        'ReadOnly',
        'questionnaire_template',
        'owner',
        'update'
    ),
    -- Delete
    (
        'Standard',
        'questionnaire_template',
        'owner',
        'delete'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template',
        'owner',
        'delete'
    ),
    (
        'ReadOnly',
        'questionnaire_template',
        'owner',
        'delete'
    ),
    (
        'InternalAudit',
        'questionnaire_template',
        'owner',
        'delete'
    );