import type { IngestedRegulatorySource } from 'src/handlers/org-event/processors/external-obligations-updated/types';

import { transformIngestionToObligationChangeset } from './transform';
import type { RegulatorChangeResult } from './types';
import { regulatorChangeResultSchema } from './types';

describe('transformIngestionChangeSet', () => {
  const data = {
    regulatorId: 'REG-001',
    providerName: 'acme',
    obligations: {
      added: [
        {
          contentHash: 'HASH_1',
          externalId: 'STANDARD-001',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          title: 'Category A Entities',
          type: 'standard',
          externalParentId: null,
        },
        {
          contentHash: 'HASH_2',
          externalId: 'STANDARD-002',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          title: 'Category B Entities',
          type: 'standard',
          externalParentId: null,
        },
        {
          contentHash: 'HASH_3',
          externalId: 'CHAPTER-001',
          externalParentId: 'STANDARD-001',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          title: 'Risk Management: Standard Framework',
          type: 'chapter',
        },
        {
          contentHash: 'HASH_4',
          externalId: 'CHAPTER-002',
          externalParentId: 'STANDARD-001',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          title: 'Asset Classification Framework',
          type: 'chapter',
        },
        {
          contentHash: 'HASH_5',
          externalId: 'CHAPTER-003',
          externalParentId: 'STANDARD-002',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          title: 'Asset Classification',
          type: 'chapter',
        },
        {
          contentHash: 'HASH_6',
          description: 'You must obey.',
          effectiveDate: '2025-08-05',
          externalId: 'RULE-001',
          externalParentId: 'CHAPTER-001',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          publishedDate: '2025-08-05',
          referenceCode: 'GRA-RMF-101.1',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          sourceUrl: 'https://example.com/rules/RULE-001',
          title: 'Simplified Assessment Methodology',
          type: 'rule',
        },
        {
          contentHash: 'HASH_7',
          description: 'Definitely do this',
          effectiveDate: '2025-08-05',
          externalId: 'RULE-002',
          externalParentId: 'CHAPTER-001',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          publishedDate: '2025-08-05',
          referenceCode: 'GRA-RMF-101.2',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          sourceUrl: 'https://example.com/rules/RULE-002',
          title: 'Simplified Assessment Methodology',
          type: 'rule',
        },
        {
          contentHash: 'HASH_8',
          description: 'Another neat rule.',
          effectiveDate: '2025-08-05',
          externalId: 'RULE-003',
          externalParentId: 'CHAPTER-002',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          publishedDate: '2025-08-05',
          referenceCode: 'GRA-ACF-201.1',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          sourceUrl: 'https://example.com/rules/RULE-003',
          title: 'Asset Classification Guidelines',
          type: 'rule',
        },
        {
          contentHash: 'HASH_9',
          description: 'Follow this with care.',
          effectiveDate: '2025-08-05',
          externalId: 'RULE-004',
          externalParentId: 'CHAPTER-002',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          publishedDate: '2025-08-05',
          referenceCode: 'GRA-ACF-201.2',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          sourceUrl: 'https://example.com/rules/RULE-004',
          title: 'Asset Classification Guidelines',
          type: 'rule',
        },
        {
          contentHash: 'HASH_10',
          description: 'This is an important rule to follow.',
          effectiveDate: '2025-08-05',
          externalId: 'RULE-005',
          externalParentId: 'CHAPTER-003',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          publishedDate: '2025-08-05',
          referenceCode: 'GRA-AC-301.1',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          sourceUrl: 'https://example.com/rules/RULE-005',
          title: 'Restricted Asset Groups and Portfolio Adjustments',
          type: 'rule',
        },
      ],
      updated: [
        {
          contentHash: 'HASH_11',
          description: 'This one has been updated since last time.',
          effectiveDate: '2025-08-05',
          externalId: 'RULE-006',
          externalParentId: 'CHAPTER-001',
          externalRegulatorId: 'REG-001',
          provider: 'acme',
          publishedDate: '2025-08-05',
          referenceCode: 'GRA-AC-106.1',
          regulatorName: 'Generic Regulatory Authority (GRA)',
          sourceUrl: 'https://example.com/rules/RULE-006',
          title: 'Updated Rule Title',
          type: 'rule',
        },
      ],
      removed: [],
    },
    obligationChanges: {
      added: [
        {
          contentHash: 'HASH_OC_1',
          description: {
            before: 'Original wording of the rule.',
            after: 'Updated wording of the rule.',
          },
          effectiveDate: '2025-09-01',
          externalId: 'OC-001',
          externalParentId: 'RULE-001',
          rationale: 'Annual policy review',
          regulatorId: 'REG-001',
          sourceUrl: 'https://example.com/changes/OC-001',
        },
        {
          contentHash: 'HASH_OC_2',
          description: {
            before: 'Previous text without rationale.',
            after: 'Updated text without rationale.',
          },
          externalId: 'OC-002',
          externalParentId: 'RULE-002',
          regulatorId: 'REG-001',
        },
      ],
      updated: [
        {
          contentHash: 'HASH_OC_3',
          description: {
            before: 'Old updated change text.',
            after: 'New updated change text.',
          },
          externalId: 'OC-003',
          externalParentId: 'RULE-001',
          regulatorId: 'REG-001',
        },
      ],
      removed: [],
    },
    previousRunId: null,
  } satisfies RegulatorChangeResult;

  it('should transform ingestion change set to IngestedObligation format', () => {
    const input = regulatorChangeResultSchema.parse(data);
    const regulatorySource: IngestedRegulatorySource = {
      id: 'REG-001',
      name: 'Generic Regulatory Authority (GRA)',
      providerName: 'acme',
    };
    const result = transformIngestionToObligationChangeset(
      regulatorySource,
      input
    );

    expect(result).toEqual({
      regulatorySource: {
        id: 'REG-001',
        name: 'Generic Regulatory Authority (GRA)',
        providerName: 'acme',
      },
      obligations: {
        added: [
          {
            contentHash: 'HASH_1',
            description: '',
            externalId: 'STANDARD-001',
            externalParentId: null,
            title: 'Category A Entities',
            type: 'standard',
            sourceUrl: null,
            regulatorySourceId: 'REG-001',
            reference: null,
          },
          {
            contentHash: 'HASH_2',
            description: '',
            externalId: 'STANDARD-002',
            externalParentId: null,
            title: 'Category B Entities',
            type: 'standard',
            sourceUrl: null,
            regulatorySourceId: 'REG-001',
            reference: null,
          },
          {
            contentHash: 'HASH_3',
            description: '',
            externalId: 'CHAPTER-001',
            externalParentId: 'STANDARD-001',
            title: 'Risk Management: Standard Framework',
            type: 'chapter',
            sourceUrl: null,
            regulatorySourceId: 'REG-001',
            reference: null,
          },
          {
            contentHash: 'HASH_4',
            description: '',
            externalId: 'CHAPTER-002',
            externalParentId: 'STANDARD-001',
            title: 'Asset Classification Framework',
            type: 'chapter',
            sourceUrl: null,
            regulatorySourceId: 'REG-001',
            reference: null,
          },
          {
            contentHash: 'HASH_5',
            description: '',
            externalId: 'CHAPTER-003',
            externalParentId: 'STANDARD-002',
            title: 'Asset Classification',
            type: 'chapter',
            sourceUrl: null,
            regulatorySourceId: 'REG-001',
            reference: null,
          },
          {
            contentHash: 'HASH_6',
            description: 'You must obey.',
            externalId: 'RULE-001',
            externalParentId: 'CHAPTER-001',
            title: 'Simplified Assessment Methodology',
            type: 'rule',
            sourceUrl: 'https://example.com/rules/RULE-001',
            regulatorySourceId: 'REG-001',
            reference: 'GRA-RMF-101.1',
          },
          {
            contentHash: 'HASH_7',
            description: 'Definitely do this',
            externalId: 'RULE-002',
            externalParentId: 'CHAPTER-001',
            title: 'Simplified Assessment Methodology',
            type: 'rule',
            sourceUrl: 'https://example.com/rules/RULE-002',
            regulatorySourceId: 'REG-001',
            reference: 'GRA-RMF-101.2',
          },
          {
            contentHash: 'HASH_8',
            description: 'Another neat rule.',
            externalId: 'RULE-003',
            externalParentId: 'CHAPTER-002',
            title: 'Asset Classification Guidelines',
            type: 'rule',
            sourceUrl: 'https://example.com/rules/RULE-003',
            regulatorySourceId: 'REG-001',
            reference: 'GRA-ACF-201.1',
          },
          {
            contentHash: 'HASH_9',
            description: 'Follow this with care.',
            externalId: 'RULE-004',
            externalParentId: 'CHAPTER-002',
            title: 'Asset Classification Guidelines',
            type: 'rule',
            sourceUrl: 'https://example.com/rules/RULE-004',
            regulatorySourceId: 'REG-001',
            reference: 'GRA-ACF-201.2',
          },
          {
            contentHash: 'HASH_10',
            description: 'This is an important rule to follow.',
            externalId: 'RULE-005',
            externalParentId: 'CHAPTER-003',
            title: 'Restricted Asset Groups and Portfolio Adjustments',
            type: 'rule',
            sourceUrl: 'https://example.com/rules/RULE-005',
            regulatorySourceId: 'REG-001',
            reference: 'GRA-AC-301.1',
          },
        ],
        updated: [
          {
            contentHash: 'HASH_11',
            description: 'This one has been updated since last time.',
            externalId: 'RULE-006',
            externalParentId: 'CHAPTER-001',
            title: 'Updated Rule Title',
            type: 'rule',
            sourceUrl: 'https://example.com/rules/RULE-006',
            regulatorySourceId: 'REG-001',
            reference: 'GRA-AC-106.1',
          },
        ],
      },
      obligationChanges: {
        added: [
          {
            externalId: 'OC-001',
            externalParentId: 'RULE-001',
            description: {
              before: 'Original wording of the rule.',
              after: 'Updated wording of the rule.',
            },
            rationale: 'Annual policy review',
            effectiveDate: '2025-09-01',
            sourceUrl: 'https://example.com/changes/OC-001',
            contentHash: 'HASH_OC_1',
            regulatorySourceId: 'REG-001',
          },
          {
            externalId: 'OC-002',
            externalParentId: 'RULE-002',
            description: {
              before: 'Previous text without rationale.',
              after: 'Updated text without rationale.',
            },
            rationale: undefined,
            effectiveDate: undefined,
            sourceUrl: undefined,
            contentHash: 'HASH_OC_2',
            regulatorySourceId: 'REG-001',
          },
        ],
        updated: [
          {
            externalId: 'OC-003',
            externalParentId: 'RULE-001',
            description: {
              before: 'Old updated change text.',
              after: 'New updated change text.',
            },
            rationale: undefined,
            effectiveDate: undefined,
            sourceUrl: undefined,
            contentHash: 'HASH_OC_3',
            regulatorySourceId: 'REG-001',
          },
        ],
      },
    });
  });
});
