table:
  name: attestation_config
  schema: risksmart
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: attestation_config
  custom_root_fields: {}
object_relationships:
  - name: createdByUser
    using:
      manual_configuration:
        column_mapping:
          CreatedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
  - name: modifiedByUser
    using:
      manual_configuration:
        column_mapping:
          ModifiedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
  - name: organisation
    using:
      foreign_key_constraint_on: OrgKey
  - name: parent
    using:
      foreign_key_constraint_on: ParentId
array_relationships:
  - name: records
    using:
      foreign_key_constraint_on:
        column: ConfigId
        table:
          name: attestation_record
          schema: risksmart
  - name: groups
    using:
      foreign_key_constraint_on:
        column: ConfigId
        table:
          name: attestation_group
          schema: risksmart
computed_fields:
  - name: timeLimitMs
    definition:
      function:
        name: attestation_time_limit_ms
        schema: risksmart
    comment: ""
insert_permissions:
  - role: Standard
    permission:
      check:
        _and:
          - OrgKey:
              _eq: X-Hasura-org-id
          - parent:
              OrgKey:
                _eq: X-Hasura-org-id
              permissions:
                _and:
                  - UserId:
                      _eq: X-Hasura-User-Id
                  - OrgKey:
                      _eq: X-Hasura-org-Id
                  - AccessType:
                      _eq: update
      set:
        CreatedByUser: x-hasura-user-id
        ModifiedByUser: x-hasura-user-id
        OrgKey: X-Hasura-org-id
      columns:
        - ParentId
        - RequireGlobalAttestation
        - AttestationTimeLimit
        - PromptText
  - role: insert:attestation-config
    permission:
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        CreatedByUser: x-hasura-user-id
        ModifiedByUser: x-hasura-user-id
        OrgKey: X-Hasura-org-id
      columns:
        - ParentId
        - RequireGlobalAttestation
        - AttestationTimeLimit
        - PromptText
select_permissions:
  - role: Public
    permission:
      columns:
        - PromptText
      filter:
        _and:
          - OrgKey:
              _eq: X-Hasura-org-id
          - records:
              OrgKey:
                _eq: X-Hasura-org-id
              UserId:
                _eq: x-hasura-user-id
  - role: Standard
    permission:
      columns:
        - ParentId
        - RequireGlobalAttestation
        - AttestationTimeLimit
        - PromptText
        - CreatedAtTimestamp
        - CreatedByUser
        - ModifiedAtTimestamp
        - ModifiedByUser
      computed_fields:
        - timeLimitMs
      filter:
        _and:
          - OrgKey:
              _eq: X-Hasura-org-id
          - parent:
              permissions:
                _and:
                  - UserId:
                      _eq: X-Hasura-User-Id
                  - OrgKey:
                      _eq: X-Hasura-org-Id
                  - AccessType:
                      _eq: read
  - role: read:attestation-config
    permission:
      columns:
        - ParentId
        - RequireGlobalAttestation
        - AttestationTimeLimit
        - PromptText
        - CreatedAtTimestamp
        - CreatedByUser
        - ModifiedAtTimestamp
        - ModifiedByUser
      computed_fields:
        - timeLimitMs
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
update_permissions:
  - role: Standard
    permission:
      columns:
        - ParentId
        - RequireGlobalAttestation
        - AttestationTimeLimit
        - PromptText
      filter:
        parent:
          OrgKey:
            _eq: X-Hasura-org-id
          permissions:
            _and:
              - UserId:
                  _eq: X-Hasura-User-Id
              - OrgKey:
                  _eq: X-Hasura-org-Id
              - AccessType:
                  _eq: update
      check:
        parent:
          OrgKey:
            _eq: X-Hasura-org-id
      set:
        ModifiedAtTimestamp: now()
        ModifiedByUser: x-hasura-user-id
  - role: update:attestation-config
    permission:
      columns:
        - ParentId
        - RequireGlobalAttestation
        - AttestationTimeLimit
        - PromptText
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        ModifiedAtTimestamp: now()
        ModifiedByUser: x-hasura-user-id
delete_permissions:
  - role: Standard
    permission:
      filter:
        _and:
          - OrgKey:
              _eq: X-Hasura-org-id
          - parent:
              permissions:
                _and:
                  - UserId:
                      _eq: X-Hasura-User-Id
                  - OrgKey:
                      _eq: X-Hasura-org-Id
                  - AccessType:
                      _eq: delete
  - role: delete:attestation-config
    permission:
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
event_triggers:
  - name: attestation_config
    definition:
      delete:
        columns: '*'
      enable_manual: true
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    webhook: https://{{REST_API_DOMAIN}}/events
    headers:
      - name: RestApiKey
        value_from_env: REST_API_KEY
