table:
  name: ingestion_config
  schema: risksmart
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: ingestion_config
  custom_root_fields: {}
object_relationships:
  - name: createdByUser
    using:
      manual_configuration:
        column_mapping:
          CreatedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
  - name: modifiedByUser
    using:
      manual_configuration:
        column_mapping:
          ModifiedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
select_permissions:
  - role: CustomerSupport
    permission:
      columns:
        - Id
        - IngestionConfig
        - SecretArn
        - CreatedByUser
        - CreatedAtTimestamp
        - ModifiedByUser
        - ModifiedAtTimestamp
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
      allow_aggregations: true
  - role: RiskManager
    permission:
      columns:
        - Id
        - IngestionConfig
        - SecretArn
        - CreatedByUser
        - CreatedAtTimestamp
        - ModifiedByUser
        - ModifiedAtTimestamp
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
      allow_aggregations: true
insert_permissions:
  - role: CustomerSupport
    permission:
      set:
        CreatedByUser: x-hasura-user-id
        ModifiedByUser: x-hasura-user-id
        OrgKey: X-Hasura-org-id
      columns:
        - IngestionConfig
        - SecretArn
      check: {}
      backend_only: true
  - role: RiskManager
    permission:
      set:
        CreatedByUser: x-hasura-user-id
        ModifiedByUser: x-hasura-user-id
        OrgKey: X-Hasura-org-id
      columns:
        - IngestionConfig
        - SecretArn
      check: {}
      backend_only: true
update_permissions:
  - role: CustomerSupport
    permission:
      columns:
        - IngestionConfig
        - SecretArn
      set:
        ModifiedByUser: x-hasura-user-id
        ModifiedAtTimestamp: now()
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
      backend_only: true
  - role: RiskManager
    permission:
      columns:
        - IngestionConfig
        - SecretArn
      set:
        ModifiedByUser: x-hasura-user-id
        ModifiedAtTimestamp: now()
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
      backend_only: true
delete_permissions:
  - role: CustomerSupport
    permission:
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
  - role: RiskManager
    permission:
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
