table:
  name: risk_assessment_result_config
  schema: risksmart
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: risk_assessment_result_config
  custom_root_fields: {}
object_relationships:
  - name: organisation
    using:
      foreign_key_constraint_on: OrgKey
  - name: createdByUser
    using:
      manual_configuration:
        column_mapping:
          CreatedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
  - name: modifiedByUser
    using:
      manual_configuration:
        column_mapping:
          ModifiedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
select_permissions:
  - role: read:risk-assessment-result-config
    permission:
      columns:
        - Id
        - Version
        - Config
        - IsLatest
        - ModifiedAtTimestamp
      filter:
        OrgKey:
          _eq: x-hasura-org-id
insert_permissions:
  - role: insert:risk-assessment-result-config
    permission:
      check:
        OrgKey:
          _eq: x-hasura-org-id
      set:
        OrgKey: x-hasura-org-id
        CreatedByUser: x-hasura-user-id
        ModifiedByUser: x-hasura-user-id
      columns:
        - Config
update_permissions:
  - role: update:risk-assessment-result-config
    permission:
      check:
        OrgKey:
          _eq: x-hasura-org-id
      set:
        ModifiedByUser: x-hasura-user-id
        ModifiedAtTimestamp: now()
      columns:
        - Config
      filter:
        OrgKey:
          _eq: x-hasura-org-id
delete_permissions:
  - role: delete:risk-assessment-result-config
    permission:
      filter:
        OrgKey:
          _eq: x-hasura-org-id