table:
  name: form_configuration
  schema: risksmart
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: form_configuration
  custom_root_fields: {}
object_relationships:
  - name: createdByUser
    using:
      manual_configuration:
        column_mapping:
          CreatedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
  - name: customAttributeSchema
    using:
      manual_configuration:
        column_mapping:
          CustomAttributeSchemaId: Id
        insertion_order: null
        remote_table:
          name: custom_attribute_schema
          schema: risksmart
  - name: modifiedByUser
    using:
      manual_configuration:
        column_mapping:
          ModifiedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
  - name: parentType
    using:
      foreign_key_constraint_on: ParentType
array_relationships:
  - name: fields_config
    using:
      foreign_key_constraint_on:
        columns:
          - FormConfigurationParentType
          - OrgKey
        table:
          name: form_field_configuration
          schema: risksmart
  - name: fields_ordering
    using:
      foreign_key_constraint_on:
        columns:
          - FormConfigurationParentType
          - OrgKey
        table:
          name: form_field_ordering
          schema: risksmart
insert_permissions:
  - role: insert:form-configuration
    permission:
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        CreatedByUser: x-hasura-user-id
        ModifiedByUser: x-hasura-user-id
        OrgKey: X-Hasura-org-id
      columns:
        - CustomAttributeSchemaId
        - ParentType
select_permissions:
  - role: read:form-configuration
    permission:
      columns:
        - CreatedAtTimestamp
        - CreatedByUser
        - ModifiedAtTimestamp
        - ModifiedByUser
        - CustomAttributeSchemaId
        - ParentType
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
update_permissions:
  - role: update:form-configuration
    permission:
      columns:
        - CustomAttributeSchemaId
        - ParentType
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        ModifiedAtTimestamp: now()
        ModifiedByUser: x-hasura-user-id
delete_permissions:
  - role: delete:form-configuration
    permission:
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
