table:
  name: form_configuration_audit
  schema: risksmart
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: form_configuration_audit
  custom_root_fields: {}
select_permissions:
  - role: read:audit
    permission:
      columns:
        - CreatedAtTimestamp
        - CreatedByUser
        - ModifiedAtTimestamp
        - ModifiedByUser
        - CustomAttributeSchemaId
        - ParentType
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
