table:
  name: sso_configuration
  schema: risksmart
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: sso_configuration
  custom_root_fields: {}
object_relationships:
  - name: createdByUser
    using:
      manual_configuration:
        column_mapping:
          CreatedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
  - name: modifiedByUser
    using:
      manual_configuration:
        column_mapping:
          ModifiedByUser: Id
        insertion_order: null
        remote_table:
          name: user_view_active
          schema: risksmart
  - name: organisation
    using:
      foreign_key_constraint_on: OrgKey
insert_permissions:
  - role: CustomerSupport
    permission:
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        CreatedByUser: x-hasura-user-id
        ModifiedByUser: x-hasura-user-id
        OrgKey: X-Hasura-org-id
      columns:
        - Name
        - Strategy
        - ClientId
        - ConnectionId
        - Domain
        - DomainAliases
        - IsActive
        - IsRestApiEnabled
        - IsOrganizationConnected
  - role: TechnicalSupport
    permission:
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        CreatedByUser: x-hasura-user-id
        ModifiedByUser: x-hasura-user-id
        OrgKey: X-Hasura-org-id
      columns:
        - Name
        - Strategy
        - ClientId
        - ConnectionId
        - Domain
        - DomainAliases
        - IsActive
        - IsRestApiEnabled
        - IsOrganizationConnected
  - role: insert:sso_configuration
    permission:
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        CreatedByUser: x-hasura-user-id
        ModifiedByUser: x-hasura-user-id
        OrgKey: X-Hasura-org-id
      columns:
        - Name
        - Strategy
        - ClientId
        - ConnectionId
        - Domain
        - DomainAliases
        - IsActive
        - IsRestApiEnabled
        - IsOrganizationConnected
select_permissions:
  - role: CustomerSupport
    permission:
      columns:
        - Id
        - OrgKey
        - Name
        - Strategy
        - ClientId
        - ConnectionId
        - Domain
        - DomainAliases
        - IsActive
        - IsRestApiEnabled
        - IsOrganizationConnected
        - CreatedAtTimestamp
        - ModifiedAtTimestamp
        - CreatedByUser
        - ModifiedByUser
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
  - role: TechnicalSupport
    permission:
      columns:
        - Id
        - OrgKey
        - Name
        - Strategy
        - ClientId
        - ConnectionId
        - Domain
        - DomainAliases
        - IsActive
        - IsRestApiEnabled
        - IsOrganizationConnected
        - CreatedAtTimestamp

        - ModifiedAtTimestamp
        - CreatedByUser
        - ModifiedByUser
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
  - role: read:sso_configuration
    permission:
      columns:
        - Id
        - OrgKey
        - Name
        - Strategy
        - ClientId
        - ConnectionId
        - Domain
        - DomainAliases
        - IsActive
        - IsRestApiEnabled
        - IsOrganizationConnected
        - CreatedAtTimestamp

        - ModifiedAtTimestamp
        - CreatedByUser
        - ModifiedByUser
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
update_permissions:
  - role: CustomerSupport
    permission:
      columns:
        - Name
        - Strategy
        - ClientId
        - ConnectionId
        - Domain
        - DomainAliases
        - IsActive
        - IsRestApiEnabled
        - IsOrganizationConnected
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        ModifiedAtTimestamp: now()
        ModifiedByUser: x-hasura-user-id
  - role: TechnicalSupport
    permission:
      columns:
        - Name
        - Strategy
        - ClientId
        - ConnectionId
        - Domain
        - DomainAliases
        - IsActive
        - IsRestApiEnabled
        - IsOrganizationConnected
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        ModifiedAtTimestamp: now()
        ModifiedByUser: x-hasura-user-id
  - role: update:sso_configuration
    permission:
      columns:
        - Name
        - Strategy
        - ClientId
        - ConnectionId
        - Domain
        - DomainAliases
        - IsActive
        - IsRestApiEnabled
        - IsOrganizationConnected
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
      check:
        OrgKey:
          _eq: X-Hasura-org-id
      set:
        ModifiedAtTimestamp: now()
        ModifiedByUser: x-hasura-user-id
delete_permissions:
  - role: CustomerSupport
    permission:
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
  - role: TechnicalSupport
    permission:
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
  - role: delete:sso_configuration
    permission:
      filter:
        OrgKey:
          _eq: X-Hasura-org-id
