table:
  name: risk_assessment_result_config_audit
  schema: risksmart
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: risk_assessment_result_config_audit
  custom_root_fields: {}
select_permissions:
  - role: read:audit
    permission:
      columns:
        - Id
        - Version
        - Config
        - IsLatest
        - CreatedByUser
        - CreatedAtTimestamp
        - ModifiedByUser
        - ModifiedAtTimestamp
      filter:
        OrgKey:
          _eq: x-hasura-org-id