import { EnvSettings } from '../env';

export const prod: EnvSettings = {
  // Must match tenant names (including case) in `tenantStack.ts`
  tenantSettings: [
    { name: 'MultiTenant', region: 'eu-west-2' },
    { name: 'OctoEnergy', region: 'eu-west-2' },
    { name: 'CanaryRisk', region: 'eu-west-2' },
    { name: 'DLA', region: 'eu-west-2' },
    { name: 'MSL', region: 'eu-west-2' },
    { name: 'JenstenGroup', region: 'eu-west-2' },
    { name: 'Education', region: 'eu-west-2' },
    { name: 'sandbox', region: 'eu-west-2' },
    { name: 'rightmove', region: 'eu-west-2' },
    { name: 'pxc', region: 'eu-west-2' },
    { name: 'autotrader', region: 'eu-west-2' },
    { name: 'krakentechnologies', region: 'eu-west-2' },
    { name: 'elementisglobal', region: 'eu-west-2' },
    { name: 'skyscanner', region: 'eu-west-2' },
    { name: 'betfred', region: 'eu-west-2' },
    { name: 'petervardy', region: 'eu-west-2' },
    { name: 'admiral', region: 'eu-west-2' },
    { name: 'hodgebank', region: 'eu-west-2' },
    { name: 'dojo', region: 'eu-west-2' },
    { name: 'amberriver', region: 'eu-west-2' },
    { name: 'gfhfinancial', region: 'eu-west-2' },
    { name: 'clearstreet', region: 'eu-west-2' },
    { name: 'rslite', region: 'eu-west-2' },
    { name: 'soprasteria', region: 'eu-west-2' },
    { name: 'mkspamp', region: 'eu-west-2' },
    { name: 'argentis', region: 'eu-west-2' },
    { name: 'mortgageadvicebureau', region: 'eu-west-2' },
    { name: 'maven', region: 'eu-west-2' },
    { name: 'gousto', region: 'eu-west-2' },
  ],
  subdomain: 'app',
  cdkStagePrefix: () => 'app',
  logRetention: 'infinite',
};
