CREATE OR REPLACE TRIGGER linked_item_insert_trigger
AFTER
INSERT ON risksmart.questionnaire_template_version REFERENCING NEW TABLE AS inserted FOR EACH STATEMENT EXECUTE PROCEDURE risksmart.linked_item_insert_with_parentid();

CREATE OR REPLACE TRIGGER linked_item_delete_trigger
AFTER DELETE ON risksmart.questionnaire_template_version REFERENCING OLD TABLE AS deleted FOR EACH STATEMENT EXECUTE PROCEDURE risksmart.linked_item_delete_with_parentid();

CREATE OR REPLACE TRIGGER linked_item_update_trigger
AFTER
UPDATE ON risksmart.questionnaire_template_version FOR EACH ROW EXECUTE PROCEDURE risksmart.linked_item_update_with_parentid();

INSERT INTO risksmart.role_access (
        "RoleKey",
        "ObjectType",
        "ContributorType",
        "AccessType"
    )
VALUES -- Read
    (
        'Standard',
        'questionnaire_template_version',
        'owner',
        'read'
    ),
    (
        'Standard',
        'questionnaire_template_version',
        'contributor',
        'read'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template_version',
        'owner',
        'read'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template_version',
        'contributor',
        'read'
    ),
    -- Insert
    (
        'Standard',
        'questionnaire_template_version',
        'owner',
        'insert'
    ),
    (
        'Standard',
        'questionnaire_template_version',
        'contributor',
        'insert'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template_version',
        'owner',
        'insert'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template_version',
        'contributor',
        'insert'
    ),
    (
        'InternalAudit',
        'questionnaire_template_version',
        'owner',
        'insert'
    ),
    (
        'InternalAudit',
        'questionnaire_template_version',
        'contributor',
        'insert'
    ),
    (
        'ReadOnly',
        'questionnaire_template_version',
        'owner',
        'insert'
    ),
    (
        'ReadOnly',
        'questionnaire_template_version',
        'contributor',
        'insert'
    ),
    -- Update
    (
        'Standard',
        'questionnaire_template_version',
        'owner',
        'update'
    ),
    (
        'Standard',
        'questionnaire_template_version',
        'contributor',
        'update'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template_version',
        'owner',
        'update'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template_version',
        'contributor',
        'update'
    ),
    (
        'InternalAudit',
        'questionnaire_template_version',
        'owner',
        'update'
    ),
    (
        'InternalAudit',
        'questionnaire_template_version',
        'contributor',
        'update'
    ),
    (
        'ReadOnly',
        'questionnaire_template_version',
        'contributor',
        'update'
    ),
    (
        'ReadOnly',
        'questionnaire_template_version',
        'owner',
        'update'
    ),
    -- Delete
    (
        'Standard',
        'questionnaire_template_version',
        'owner',
        'delete'
    ),
    (
        'StandardEnhanced',
        'questionnaire_template_version',
        'owner',
        'delete'
    ),
    (
        'ReadOnly',
        'questionnaire_template_version',
        'owner',
        'delete'
    ),
    (
        'InternalAudit',
        'questionnaire_template_version',
        'owner',
        'delete'
    );