import type { AsyncRequestEvent, BaseEvent } from './common';
import type { OrgUserEvent } from './orguser-events';

export type CommandTypeNames =
  | 'CREATE_ACCEPTANCE'
  | 'CREATE_ACTION_UPDATE'
  | 'CREATE_ACTION'
  | 'CREATE_APPETITE'
  | 'CREATE_ASSESSMENT'
  | 'CREATE_CAUSE'
  | 'CREATE_CONSEQUENCE'
  | 'CREATE_CONTROL_GROUP'
  | 'CREATE_CONTROL_TEST_RESULT'
  | 'CREATE_CONTROL'
  | 'CREATE_FORM_FIELD'
  | 'CREATE_LINKED_ITEM'
  | 'CREATE_INDICATOR_RESULT'
  | 'CREATE_ISSUE_ASSESSMENT'
  | 'CREATE_ISSUE_UPDATE'
  | 'CREATE_ISSUE'
  | 'CREATE_OBLIGATION_IMPACT'
  | 'CREATE_OBLIGATION'
  | 'CREATE_RISK_ASSESSMENT_RESULT'
  | 'CREATE_RISK'
  | 'CREATE_SSO_CONFIGURATION'
  | 'CREATE_USER_GROUP'
  | 'DELETE_ACCEPTANCES'
  | 'DELETE_ACTION_UPDATES'
  | 'DELETE_APPETITES'
  | 'DELETE_ASSESSMENT'
  | 'DELETE_CAUSES'
  | 'DELETE_CONSEQUENCES'
  | 'DELETE_CONTROL_GROUP'
  | 'DELETE_FORM_FIELD'
  | 'DELETE_INDICATOR_RESULTS'
  | 'DELETE_INDICATORS'
  | 'DELETE_ISSUES'
  | 'DELETE_ISSUE_UPDATES'
  | 'DELETE_LINKED_ITEM'
  | 'DELETE_OBLIGATION_IMPACTS'
  | 'DELETE_RISK'
  | 'DELETE_SSO_CONFIGURATION'
  | 'DELETE_TEST_RESULTS'
  | 'UPDATE_ACCEPTANCE'
  | 'UPDATE_APPETITE'
  | 'UPDATE_ASSESSMENT'
  | 'UPDATE_CAUSE'
  | 'UPDATE_CONSEQUENCE'
  | 'UPDATE_FORM_FIELD'
  | 'UPDATE_INDICATOR_RESULT'
  | 'UPDATE_INDICATOR'
  | 'UPDATE_ISSUE'
  | 'UPDATE_RISK'
  | 'UPDATE_TEST_RESULT';

export type InitiateAsyncRequest<TRequest> = OrgUserEvent<{
  request: TRequest;
  subType: CommandTypeNames;
}> & {
  type: AsyncRequestEvent.InitiateAsyncRequest;
};

export type UpdateAsyncRequest<TRequest, TMetadata> = BaseEvent<
  {
    request: TRequest;
  },
  TMetadata
> & { type: AsyncRequestEvent.UpdateAsyncRequest };
